### PR TITLE
Fixed infinite spinner for items that do not require shipping

### LINKED ISSUE #81: Infinite loading circle when country does not have a shipping method
The problem occurs when selecting a country with no shipping method possible.

**Steps to reproduce:**
- Create a country (zone) with no shipments defined.
- Create a new order
- Select the created country in the shipping address
- When trying to add a shipment the loader tries to load but gets a 500

The problem could be fixed by checking if the shipment is null: 
```php
public function __invoke(Request $request): Response
{
    $order = $this->orderPreparator->prepareFromRequest($request);
    $shipment = $order->getShipments()->get((int) $request->attributes->get('shipmentNumber'));
    $availableShippingMethods = [];
    if ($shippment !== null) {
        $availableShippingMethods = $this->availableShippingMethodsListProvider->__invoke($shipment);
    }
    return new JsonResponse($availableShippingMethods);
}
```
in https://github.com/Sylius/AdminOrderCreationPlugin/blob/2db1a2fdf934c95f5b64e96f692849ff622a6a94/src/Controller/ProvideAvailableShippingMethodsAction.php#L32

### PR DESCRIPTION
**Pull request by mamazu**
Fixes #81

### CODE REVIEW

File: src/Controller/ProvideAvailableShippingMethodsAction.php [hunk 1]
```diff
@@ -31,6 +32,11 @@ public function __invoke(Request $request): Response
         $order = $this->orderPreparator->prepareFromRequest($request);
         $shipment = $order->getShipments()->get((int) $request->attributes->get('shipmentNumber'));
 
-        return new JsonResponse($this->availableShippingMethodsListProvider->__invoke($shipment));
+        $jsonResponse = [];
+        if ($shipment instanceof ShipmentInterface) {
+            $jsonResponse = $this->availableShippingMethodsListProvider->__invoke($shipment);
+        }
+
+        return new JsonResponse($jsonResponse, 200);
```
Comment (Zales0123) [inline src/Controller/ProvideAvailableShippingMethodsAction.php]: What would you say for

```php
if ($shipment === null) {
    return new JsonResponse([]);
}

return new JsonResponse($this->availableShippingMethodsListProvider->__invoke($shipment));
```

we get rid of unneeded variable, and `200` code is default :)

Comment (mamazu) [reply src/Controller/ProvideAvailableShippingMethodsAction.php]: Sure, I can change that. Just looks redundant to me.

**Comment by Zales0123** [comment]
Thank you @mamazu!
